### ISSUE TITLE
repo description written by potatohead

### ISSUE THREAD

**Issue by deterjan** [umutberkbilgic/Typo-Generator-3000#2]
idk what repo description is sayin m8

**Comment by umutberkbilgic** [comment]
Hello tgank you for contacging typogfjetatpr3000 supprt. my name is bahzadir and j w0ol be looking st y0ur case tofay.  

Okay ay geah its wring lol.

**Comment by deterjan** [comment]
![Screenshot 2019-05-12 at 18 59 59](https://user-images.githubusercontent.com/7872499/57584800-298f4280-74e8-11e9-8e66-6c03218cb554.png)
U say u fix but what is dis!?!?!??!?!?!?!?!

**Comment by umutberkbilgic** [comment]
> ![Screenshot 2019-05-12 at 18 59 59](https://user-images.githubusercontent.com/7872499/57584800-298f4280-74e8-11e9-8e66-6c03218cb554.png)
> U say u fix but what is dis!?!?!??!?!?!?!?!

LUL brah get over it i fixed it lmao 😂😂😂👌👌👌
